name: show_ai_dev
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.0
  http: ^1.2.2
  workmanager: ^0.5.1
  flutter_local_notifications: ^17.2.4
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.jpg"
  web:
    generate: true
    image_path: "assets/icon/logo.jpg"
    background_color: "#1A1A1A"
    theme_color: "#2D2D2D"

flutter:
  uses-material-design: true
